INK2-764-library-changes
Shopify/sarama pull request #1794
Opened 2020-09-02 22:59 UTC by arora01gunjan

2020-09-08 04:50 UTC, dackroyd requested changes

2020-09-08 04:50 UTC, dackroyd commented on fetch_response.go
> +	"bitbucket.org/ffxblue/bp-gateway/pkg/monolog"
Internal project packaging, unrelated to Sarama, Need to remove all internal code references/use

2020-09-08 04:50 UTC, dackroyd commented on fetch_response.go
> -	rec := &Record{Key: kb, Value: vb, OffsetDelta: offset, TimestampDelta: timestamp.Sub(batch.FirstTimestamp)}
Fundamentally the issue here is that it needs to be possible to include headers in the record, not these specific ones?

2020-09-08 04:51 UTC, dackroyd commented
It's likely that we can keep these changes within the fork, without a PR back to the main repo for now

2020-11-06 15:52 UTC, dnwe commented
From the comments above it sounds like this was an accidentally raised PR containing some code to set a number of default record headers based on a private company project?

Will go ahead and close this PR for now but feel free to come back if you think I'm mistaken :)

2020-11-06 15:52 UTC, closed without merging